#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Aug 25 15:36:19 IST 2026
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto c502d655921e4a2db7bf8ff3bd06e5e7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot mealy_detector_tb_behav xil_defaultlib.mealy_detector_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto c502d655921e4a2db7bf8ff3bd06e5e7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot mealy_detector_tb_behav xil_defaultlib.mealy_detector_tb xil_defaultlib.glbl -log elaborate.log

